### ISSUE TITLE
any chance to have update for QGIS 3xxx

### ISSUE THREAD

**Issue by jipexu** [florianhof/ToporobotImporter#2]
Hi great works
any chance to have a new release for QGIS 3 ??

Thanks

**Comment by florianhof** [comment]
Hi, thanks for testing on QGIS 3. I'll have a look at it on the week-end. I'm of course interested that the plugin further lives.

**Comment by jipexu** [comment]
@florianhof 
thanks!
 I finally install 2 version of QGIS to continue to work with ...  (i tried to update but i am absolute beginner in PY ! .... so even after read some doc to upgrade QGIS 2 > QGIS 3 plugins i gave up ...)
i known toporobot is no more maintened but we have lot of archives to works with  and some software continue to give output in toporobot format so an update of Toporobotimporter will be very great !!

**Comment by florianhof** [comment]
Work ongoing on branch [feature/migration_qgis3](https://github.com/florianhof/ToporobotImporter/commits/feature/migration_qgis3)
Started with instructions on https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3
Still not so far on migration, will takes some time...

**Comment by jipexu** [comment]
great !

**Comment by jipexu** [comment]
tell me when i can start to test ..

**Comment by florianhof** [comment]
HI @jipexu , now I have a working alpha version for a simple case. See last commit's message for known limitations and bugs. Thanks for testing ... if possible also with a digital elevation model. Here the zipped plugin: [ToporobotImporter.zip](https://github.com/florianhof/ToporobotImporter/files/4173932/ToporobotImporter.zip)

**Comment by jipexu** [comment]
thanks great on the way for testing ! 
i will try with shuanghedong data who is the longest cave of china 280 km  > 30 000 stations
and can compare with the last version of the pluggin ...

**Comment by jipexu** [comment]
humm
when i try to import the files
Error UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 3910: invalid start byte

**Comment by jipexu** [comment]
also get this

Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'QgsFileWidget' object has no attribute 'clear' 
Traceback (most recent call last):
  File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ToporobotImporter/topoimpDialog.py", line 130, in 
    return lambda: self.browseForOutShapefile(lineedit)
  File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ToporobotImporter/topoimpDialog.py", line 125, in browseForOutShapefile
    lineedit.clear()
AttributeError: 'QgsFileWidget' object has no attribute 'clear'


Version de Python : 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
Version de QGIS : 3.10.2-A Coruña A Coruña, 616ad4531b

**Comment by florianhof** [comment]
The second error (by _lineedit.clear()_) is when using _browse_ button. Use meanwhile the first _..._ button or drag-and-drop a file on the field. I'll of course fix this. 
The second error is more difficult to analyse. Have you the full error message? Which encoding have your various input files? (mac-roman, iso-8859-1, windows..., utf-8?) Have they chineese characters?

**Comment by jipexu** [comment]
just to precise the file are the same that i used with the previous version of Toporobotimporter (without problemes ...)
let me check what encoding i have for those 2 files ...
both have Western (Mac OS Roman) and Legacy Mac (CR)

i try to change the encoding to utf-8 and Unix(LF) to see what happen's ....

**Comment by jipexu** [comment]
ok better now
i change the encoding and end line so no more encoding error ...
for the second error i found only one way
i have to create an empty shp file before then choose this file  this work ... if i have not this empty file i found no way to escape this error ...

**Comment by florianhof** [comment]
new version [ToporobotImporter.zip](https://github.com/florianhof/ToporobotImporter/files/4233716/ToporobotImporter.zip)...
The encoding can now be changed in the UI. 
All end-of-line are handled properly (unix, mac-classic, windows), this is unit-tested. 
There are still 2 buttons to pick file, the second one fits better the reality.

**Comment by jipexu** [comment]
i will test soon

**Comment by pucicu** [comment]
Thanks, Flo, for the update! It saved my night! And thanks for this very helpful tool. I use it for our research in Sägistal.

**Comment by jipexu** [comment]
Hi there
I meet some new problem with QGIS 3.22.3 ...
Become less stable with this version ?...

Can not import station as line, station as surface ... the import process seems ok BUT it make truncated files ...(station as point is still ok ..)
here is the type of error (who is not present during the station point import)
`2022-02-23T15:26:52     WARNING    Erreur lors de la conversion de la valeur (2001-04-03) pour le champ d'attribut TRIP_DATE : La chaîne de longueur 10 dépasse le maximum de longueur de champ (8)`
and repeated many times ... on each conversion...

i have modified the length in topoDrawer.py line 233 ... and it's work ... even i still not understand why those error are not present for the stations as point ?
`fieldsForStations.append(QgsField('TRIP_DATE' , QVariant.String, 'varchar',  10, 0, "trip's date"))
`

and also this general error
```
2022-02-23T15:26:52     WARNING    warning:/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ToporobotImporter/topoimpProcess.py:228: DeprecationWarning: QgsVectorFileWriter constructor is deprecated
              writer = QgsVectorFileWriter(outPath, 'UTF-8', drawer.fields(), drawer.wkbType(), self.srs, "ESRI Shapefile")
```





Thanks
